[package]
name = "mnist"
version = "0.1.0"
authors = ["Nasser Idirene <nasser.idirene@gmail.com>"]
edition = "2018"
description = "MNIST utils"
license = "MIT"
[dependencies]
ndarray = "^0.13.1"
byteorder = "^1.3.4"
png = "^0.16.3"

